# Generated by Django 4.2 on 2023-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Adresse_email',
            field=models.EmailField(max_length=254),
        ),
    ]
