# Generated by Django 4.2 on 2023-05-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_adresse_email'),
    ]

    operations = [
    ]
