# Generated by Django 4.2 on 2023-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230517_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='sing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lasr_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bac', models.IntegerField()),
                ('deplom', models.CharField(max_length=50)),
            ],
        ),
    ]
