# Generated by Django 4.2 on 2023-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_delete_sing'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='my_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='prof',
            field=models.BooleanField(default=False),
        ),
    ]
