# Generated by Django 4.2 on 2023-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_user_rename_my_field_student_verfed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mention_bac',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mention_diplome',
            field=models.CharField(max_length=100),
        ),
    ]
