# Generated by Django 4.2 on 2023-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_student_mention_bac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='verfed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cne', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=200)),
                ('specialite_bac', models.CharField(max_length=100)),
                ('annee_obtention_bac', models.IntegerField()),
                ('mention_bac', models.CharField(max_length=100)),
                ('diplome_obtenu', models.CharField(max_length=100)),
                ('specialite_diplome', models.CharField(max_length=100)),
                ('annee_obtention_diplome', models.IntegerField()),
                ('mention_diplome', models.CharField(max_length=100)),
                ('prof', models.BooleanField(default=False)),
                ('verfed', models.BooleanField(default=False)),
            ],
        ),
    ]
