# Generated by Django 4.2 on 2023-05-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_verfed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='verfed',
            new_name='verfeed',
        ),
    ]
