# Generated by Django 4.2 on 2023-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_verfed_verfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verfeed',
            name='verfed',
            field=models.BooleanField(default=True),
        ),
    ]
