# Generated by Django 4.2 on 2023-05-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_modules_remove_student_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='module',
            new_name='title',
        ),
    ]
